### ISSUE TITLE
ticket page/menu

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#13]
I can't seem to find the ticket page - and forgot how to access menu

*****also I just noticed there were no ticketpro links for any of the shows. I have sent Patti a note - I hope she hasn't been entering them in the wrong place or that they've gotten lost...

**Comment by andrewfn** [comment]
http://torontojazz.com/tickets
- Main menu is here and you can see that the tickets link is disabled:

http://torontojazz.com/admin/structure/menu/manage/main-menu
