### ISSUE TITLE
Calendar page changes

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2015#2]
on the At-a-glance, let's try to dress it up a little this year - even if it's just use the home page header or something to make it look like it's part of the same site.
Also, you will need to add sun 28 and mon 29 (even though there's just a couple of shows on the sun and one (Jamie Cullum) on the Monday.
submitted by @brianblain

**Comment by andrewfn** [comment]
re Sun 28 and Mon 29
I created them in the original calendar and they always show for me (as mostly-empty columns).
Can you verify that they are not showing for you? (make sure you are logged in)
@andrewnl

**Comment by brianblain** [comment]
yes - they are showing. I was confusing with the excel grid

**Comment by brianblain** [comment]
still hoping to have the at-a-glace page looking a bit more like the rest of the site.  The printable version can be plain (though I notice it doesn't display 28 & 29 and I can see how it would be a real squeeze to get them in - maybe there's a way to display Jaime Cullum on the 29th somewhere else - bottom of list??

It would also be great if the at-a-glace highlighted the big shows, either by putting them at the top of the list...or maybe some shading??

**Comment by andrewfn** [comment]
I'm planning to work on improving the look, and also do the printable version.
Also highlight the big shows.

**Comment by andrewfn** [comment]
What would you think of having a mini picture of the artists in the calendar?
I'm thinking of something like the home page, but half the size so it all fits in.

**Comment by brianblain** [comment]
sure, why not.  But if it makes it look too cluttered, I'd be fine with
just a nicer frame

On Mon, Apr 13, 2015 at 6:46 PM, Andrew Fountain notifications@github.com
wrote:

> What would you think of having a mini picture of the artists in the
> calendar?
> I'm thinking of something like the home page, but half the size so it all
> fits in.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2015/issues/2#issuecomment-92521788.

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by andrewfn** [comment]
You can take a sneak peak at my development version and tell me what you think (bear in mind that there will be more color coming to replace the grey and white).
http://dev.jazz.to/caltest/rebuild

**Comment by brianblain** [comment]
I don't know about the photos, Andrew.  It kinda defeats the "at-a-glance"
concept....

On Mon, Apr 13, 2015 at 9:58 PM, Andrew Fountain notifications@github.com
wrote:

> You can take a sneak peak at my development version and tell me what you
> think (bear in mind that there will be more color coming to replace the
> grey and white).
> http://dev.jazz.to/caltest/rebuild
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2015/issues/2#issuecomment-92558018.

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by andrewfn** [comment]
I actually think it's faster for glancing at because once you know what a pic looks like you can find it **much** more quickly than searching for the text.
However I could make the pics a bit smaller so as to make it more compact.

**Comment by brianblain** [comment]
well, as long as we can get something presentable for tomorrow.  It was running off the page.  I'm more concerned with highlighting the big shows (bringing them to the top...)

(There WILL be a couple of new venues added)

**Comment by andrewfn** [comment]
Highlighting the big shows will be a priority

**Comment by brianblain** [comment]
whatever we need to do to make it presentable for tomorrow

**Comment by brianblain** [comment]
also, many of the lesser clubs didn't have pics, and this makes it so obvious (now scrambling to find more pics for lesser artists)

**Comment by andrewfn** [comment]
For me as a user that is a plus because it helps me identify the more major
shows

**Comment by brianblain** [comment]
maybe if we put a generic graphic silhouette as a default if there is no pic?

**Comment by andrewfn** [comment]
That is actually what I have now, but it is transparent. I could put a light grey box in instead.
Don't forget that the same problem occurs on all our other concert listings, like the daily ones. Half the pictures are missing and we haven't worried about it!

**Comment by brianblain** [comment]
maybe use this as a placeholder for artists that don't have a pic.  we are still adding pics

![jazzguy-250](https://cloud.githubusercontent.com/assets/11864078/7130261/fc0f6450-e23a-11e4-9349-8b07f13138f0.jpg)

**Comment by brianblain** [comment]
good morning Andrew - just got our ticketpro links and I will start punching them in.  where are we at with this calendar?

**Comment by andrewfn** [comment]
New version of calendar will go up soon.
I assume that there are no concerts on Sun Jun 28 so it would be tidier not to show the column?

**Comment by brianblain** [comment]
pat thought there would be (jazz bistro, distillery). Also, Jamie cull im
is sold out. I was thinking that could be placed separately maybe in a box
that would fit in top right corner to make it nicer. B

On Tuesday, April 14, 2015, Andrew Fountain notifications@github.com
wrote:

> New version of calendar will go up soon.
> I assume that there are no concerts on Sun Jun 28 so it would be tidier
> not to show the column?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2015/issues/2#issuecomment-92874867.

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by brianblain** [comment]
Distillery is not on the grid but was confirmed yesterday

On Tuesday, April 14, 2015, Brian Blain blain@tojazz.com wrote:

> pat thought there would be (jazz bistro, distillery). Also, Jamie cull im
> is sold out. I was thinking that could be placed separately maybe in a box
> that would fit in top right corner to make it nicer. B
> 
> On Tuesday, April 14, 2015, Andrew Fountain <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > New version of calendar will go up soon.
> > I assume that there are no concerts on Sun Jun 28 so it would be tidier
> > not to show the column?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/jazzto/2015/issues/2#issuecomment-92874867.
> 
> ## 
> 
> Brian Blain
> Managing Editor
> Toronto Downtown Jazz
> 82 Bleecker Street, Toronto, ON  M4X 1L8
> blain@tojazz.com <javascript:_e(%7B%7D,'cvml','blain@tojazz.com');>
> 
> www.torontojazz.com
> TD Toronto Jazz Festival
> June 18-27, 2015

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by andrewfn** [comment]
So there are some Sunday shows then?

**Comment by brianblain** [comment]
But not booked yet

On Tuesday, April 14, 2015, Andrew Fountain notifications@github.com
wrote:

> So there are some Sunday shows then?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2015/issues/2#issuecomment-92889659.

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by andrewfn** [comment]
Take a look at this (using your idea of the jazz man when there is no pic)
http://dev.jazz.to/calendar2/rebuild

**Comment by brianblain** [comment]
OK let's roll with that.  See what everybody says.  I'm heading out
shortly.  Did you fix the links on ticket page?

On Tue, Apr 14, 2015 at 12:15 PM, Andrew Fountain notifications@github.com
wrote:

> Take a look at this (using your idea of the jazz man when there is no pic)
> http://dev.jazz.to/calendar2/rebuild
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2015/issues/2#issuecomment-92942974.

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by andrewfn** [comment]
The last thing I have to do is to highlight the main shows by putting them at the top.
Here's a question: I actually have to put the whole venue line containing the main show at the top--is that ok?

**Comment by brianblain** [comment]
patti just added a couple more noontime shows at Nathan Phillips.  Not great that they would be the first things to show...maybe leave as is and make it live on the test site.  We'll prioritize later

**Comment by andrewfn** [comment]
Actually I think those show as a different series.
I have picked four locations to be at the top (and given you a way you can change this) Have a look and see:
http://dev.jazz.to/calendar2/rebuild

**Comment by brianblain** [comment]
Can you put Nathan Phillips at very top then we'll be OK

On Tue, Apr 14, 2015 at 1:01 PM, Andrew Fountain notifications@github.com
wrote:

> Actually I think those show as a different series.
> I have picked four locations to be at the top (and given you a way you can
> change this) Have a look and see:
> http://dev.jazz.to/calendar2/rebuild
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2015/issues/2#issuecomment-92981683.

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by brianblain** [comment]
is mobile ready to go?

On Tue, Apr 14, 2015 at 1:05 PM, Brian Blain blain@tojazz.com wrote:

> Can you put Nathan Phillips at very top then we'll be OK
> 
> On Tue, Apr 14, 2015 at 1:01 PM, Andrew Fountain <notifications@github.com
> 
> > wrote:
> > 
> > Actually I think those show as a different series.
> > I have picked four locations to be at the top (and given you a way you
> > can change this) Have a look and see:
> > http://dev.jazz.to/calendar2/rebuild
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/jazzto/2015/issues/2#issuecomment-92981683.
> 
> ## 
> 
> Brian Blain
> Managing Editor
> Toronto Downtown Jazz
> 82 Bleecker Street, Toronto, ON  M4X 1L8
> blain@tojazz.com
> 
> www.torontojazz.com
> TD Toronto Jazz Festival
> June 18-27, 2015

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by brianblain** [comment]
heading out now - I'll check in from jazzFM

On Tue, Apr 14, 2015 at 1:06 PM, Brian Blain blain@tojazz.com wrote:

> is mobile ready to go?
> 
> On Tue, Apr 14, 2015 at 1:05 PM, Brian Blain blain@tojazz.com wrote:
> 
> > Can you put Nathan Phillips at very top then we'll be OK
> > 
> > On Tue, Apr 14, 2015 at 1:01 PM, Andrew Fountain <
> > notifications@github.com> wrote:
> > 
> > > Actually I think those show as a different series.
> > > I have picked four locations to be at the top (and given you a way you
> > > can change this) Have a look and see:
> > > http://dev.jazz.to/calendar2/rebuild
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jazzto/2015/issues/2#issuecomment-92981683.
> > 
> > ## 
> > 
> > Brian Blain
> > Managing Editor
> > Toronto Downtown Jazz
> > 82 Bleecker Street, Toronto, ON  M4X 1L8
> > blain@tojazz.com
> > 
> > www.torontojazz.com
> > TD Toronto Jazz Festival
> > June 18-27, 2015
> 
> ## 
> 
> Brian Blain
> Managing Editor
> Toronto Downtown Jazz
> 82 Bleecker Street, Toronto, ON  M4X 1L8
> blain@tojazz.com
> 
> www.torontojazz.com
> TD Toronto Jazz Festival
> June 18-27, 2015

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by andrewfn** [comment]
Looks good to me. Check it out on http://test.jazz.to
