### ISSUE TITLE
links on ticket page

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#21]
I think you will have to do this

on ticket page, "3 show"  should link to: https://tprotjf.ticketpro.ca/?server=ww2&aff=tjf&lang=en#combo2_TorontoJazzFestival3SHOW

"5 show" should link to: https://tprotjf.ticketpro.ca/?server=ww2&aff=tjf&lang=en#combo2_TorontoJazzFestival5SHOW

**Comment by andrewfn** [comment]
Which page?
not http://torontojazz.com/tickets

**Comment by brianblain** [comment]
yes that's the page.

**Comment by andrewfn** [comment]
Did it. If you want to do this yourself it's very easy. You use double square brackets like:
**[[**http://link-to-site _link text_**]]**

**Comment by brianblain** [comment]
thanks

On Tue, Apr 14, 2015 at 1:06 PM, Andrew Fountain notifications@github.com
wrote:

> Closed #21 https://github.com/jazzto/2015/issues/21.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2015/issues/21#event-281182129.

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015
