### ISSUE TITLE
oscar peterson pic for Jane Mallett

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#23]
we want to display a pic of Oscar instead of Robi Botos which appears.  Can we put a pic of Oscar as part of thew event page (I thought we could put pics for the shows...)

**Comment by andrewfn** [comment]
- Create Oscar as an artist (This would be a good place to paste in a bio)
- Upload his picture to his page
- Add him to the concert page (It will be obvious that he is not playing, but it will have the effect of adding his bio to the concert page which would be good.)
- Put him first in the list which will make his photo appear.

**Comment by andrewfn** [comment]
I made the changes as above, but I don't have any artist info.
You should paste in some kind of a bio for the quartet or the page looks empty.
The picture now shows up.

**Comment by brianblain** [comment]
I copied the blurb from the event page onto the OP artist page but it does not display (??)

**Comment by andrewfn** [comment]
It looks fine to me. Did you do something to fix it?

**Comment by brianblain** [comment]
Looks like the text found it's place.  Now I tried to change the artist name to "...celebration" instead of "OP Quartet" It changed on the artists page but not on the event page (??)

also, the address bar in the browser also displays the previous artist name.  I guess some things are "sticky"

**Comment by andrewfn** [comment]
If you want to change the URL then you can do it at the bottom of the page under the **URL path settings** tab.
The reason it does not change it automatically is that if the page is being linked to from elsewhere (e.g. a concert-goer might have bookmarked the page on their computer) then changing the URL will break all such links. If it's a new page, then there's not much of a risk.
