### ISSUE TITLE
news item won't display

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#26]
I probably forgot a step but I added a news item - it displays like it should when I'm logged in but does not appear on my other browser which is not logged in

**Comment by andrewfn** [comment]
About 50% of the issues coming up are related to the cache on the server which is cleared ever hour.
You can force it to clear by going to the **Performance** page:
http://torontojazz.com/admin/config/development/performance
and pressing the **(Clear all caches)** button.
_Please could you verify that you have permission to access this page?_

**Comment by brianblain** [comment]
access denied.  and I've just tried to replace the presskit on the media page and having trouble (maybe due to this) Please refresh & give me permission

**Comment by andrewfn** [comment]
I gave you the wrong link.
This one will do it and you have permission. Just clicking on the link flushes the cache and returns you to the hope page.
http://torontojazz.com/admin/content/flush-cache
