### ISSUE TITLE
concert page display- youube display

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#29]
can we have the youtube display on the concert page as well as the artist page

**Comment by andrewfn** [comment]
Yes, I think I can do that.

**Comment by brianblain** [comment]
have you had another look at this?  The audio player displays with concert but video doesnt

**Comment by andrewfn** [comment]
It's on my things to do list, but I'll bump it to a higher priority.

**Comment by andrewfn** [comment]
Video now displaying correctly.
