### ISSUE TITLE
dev site

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2015#3]
Can we have a dev site working end of week so we can see how the home page will look?
@brianblain

**Comment by brianblain** [comment]
this will make things move along a lot faster if we can see at a glance who's got photos and who doesn't

**Comment by andrewfn** [comment]
Here's a start: http://dev.jazz.to/
I realize I'll have to enable the search boxes as well. I'll do that tomorrow.

**Comment by brianblain** [comment]
even if you just have the date boxes, that will be enough for us  to go through and see what remains to be done, photo-wise. Did I mention we go live on Tues?

**Comment by andrewfn** [comment]
I had no idea. You need to tell me these things sooner!
Aiming to get dev fully running by lunchtime.

**Comment by brianblain** [comment]
sorry about that, man. I had assumed...and one should never make assumptions!

**Comment by andrewfn** [comment]
Check it out now and let me know of any problems.
I can see that there are too many dates to fit on one line, so I'll be looking at that.

**Comment by brianblain** [comment]
That's great! remind me if we have to be careful what/where we input new
content.  For ex, I have to put the letters from mayor & TD - do I do that
on dev or the live site?

On Fri, Apr 10, 2015 at 12:23 PM, Andrew Fountain notifications@github.com
wrote:

> Check it out now and let me know of any problems.
> I can see that there are too many dates to fit on one line, so I'll be
> looking at that.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2015/issues/3#issuecomment-91607475.

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by andrewfn** [comment]
Don't make any changes to the dev site because it is blown away every few hours when I refresh it from the live site.
I'm about to do another refresh but you can let me know any time you particularly need to see the latest data.

**Comment by andrewfn** [comment]
From now on please use http://test.torontojazz.com as the test site.
- One reason for this is that you can also test mobile with this site, using http://test.jazz.to
- Also I can more easily keep it regularly updated from the main site.
- As before, any changes made to this test site will be lost
