### ISSUE TITLE
wishlist

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#31]
can you remind me how to retrieve it?

**Comment by andrewfn** [comment]
If you look at the issue where you wanted it removed: https://github.com/jazzto/2015/issues/8
and just reverse the operations, that should do it!

**Comment by brianblain** [comment]
it's not the ad I want to retrieve it"s the data that's been collected (in excel format, as I recall)

**Comment by andrewfn** [comment]
Ah right. The trick is to find the form once it is disabled, but once you have that it is easy.
I think this is your form: http://torontojazz.com/artists-suggestions-2015-festival
- Click on the **results** tab 
- the **Download** button will get you a spreadsheet.
- If you just want to take a look, the **table** button will do that
