### ISSUE TITLE
mobile site seems to be going to test.jazz.to

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#33]

**Comment by andrewfn** [comment]
I'm checking into it.

**Comment by andrewfn** [comment]
It's going to the right site but for some reason is not updating. (Your news story is not showing.).
I'll find out why and fix it.

**Comment by andrewfn** [comment]
It was an obscure bug but I have tracked it down and fixed it.
All seems to be working well now. (It can be a pain to try and get the browser on a phone to refresh its cache.)
@joshgrossman
