### ISSUE TITLE
more shows on mobile home page

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#40]
PTT is asking if we could have the mobile display more than just 12 shows on the landing page. There's more Headline shows we could add and maybe even include priority 2...what do you think?

**Comment by andrewfn** [comment]
No problem at all. Just tell me how many you want and I'll set it.

**Comment by brianblain** [comment]
let's say 30-36 (that would about cover all the headline 1 & 2 shows)
- this is just for the mobile display, eh?

**Comment by andrewfn** [comment]
I've changed it to 30. Have a look and tell me what you think or if it needs to go to 36
