### ISSUE TITLE
midnight jams not displaying correctly

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#43]
Here we go again with the midnight show problem (is it today or is it tomorrow?)  Suggestions?

There are 6 jams in total 12midnight - 3am

Fri June 19 & Sat. June 20  & Tues. June 23 Late Night Jazz Jam w/ Morgan Childs Trio

Thurs. June 25 & Sat. June 27 Late Night Jazz Jam w/ Chris Gale Quartet

Fri. June 26 Late Night Jazz Jam w/ George Garzone Berklee Quartet

Nothing on Sunday 28th

**Comment by andrewfn** [comment]
Yes I have an idea what we can do.
I have to automatically create another (internal) field which will be the date and time in another timezone (e.g. Vancouver time). I would use that to decide which date to show it on. I'll have a play with it and see what I can come up with.

**Comment by brianblain** [comment]
Patti was asking about this again.  I guess the venue is on her case...

**Comment by andrewfn** [comment]
I think I have got it working now. It took an incredible 10 hours of programming but it should have dealt with the problem once and for all. Let me know if it is good, and close the issue if it is.

**Comment by brianblain** [comment]
so the event displays "all day" though the time is set at 00:00.  Can we just put midnight in there or how do we do it?

**Comment by andrewfn** [comment]
The system is assuming that 00:00 means all day. I think there might be a fix--just looking for it.

**Comment by andrewfn** [comment]
I have fixed it. Midnight shows now show as starting at 00:00am

**Comment by brianblain** [comment]
just noticed patti had set time to 11:45pm for those midnight jams so I changed one to 00:00 and it moved to the _previous_ day....I think we can make do with 11:45...

**Comment by andrewfn** [comment]
This is what you would expect since she changed time to the previous day at 11:45.
When you set it to 00:00 you need to set it to the next day since that is the day it technically falls on.
Then it will display on the correct day.

**Comment by brianblain** [comment]
ill try that

On Tue, Jun 16, 2015 at 12:04 AM, Andrew Fountain notifications@github.com
wrote:

> Closed #43 https://github.com/jazzto/2015/issues/43.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2015/issues/43#event-331701294.

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015
