### ISSUE TITLE
tdj news corps 2015

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2015#45]
We're ready to go with the 2015 edition of the TDJ News Corps.  I'll send you new text for torontojazz.com/tdj-news; in the meantime, could you please create login credentials for:
- Stephanie Matas
- Cameron MacDonald

As in past years, they should have privileges to create unpublished TDJ News Corps entries only; I'll publish each piece once it's been given a final review.
@joshgrossman

**Comment by andrewfn** [comment]
I would need their email addresses to do that.
It is actually much simpler if you ask them to create accounts for themselves and and as soon as they do I will upgrade their privileges. That way I don't have to make up passwords for them and get all their info correct.

**Comment by joshgrossman** [comment]
Okay - stay tuned...I'll ask them to set up their own accounts.

Josh

**Comment by joshgrossman** [comment]
Okay - usernames are:

cameron.macdonald
stephmatas

Please also update torontojazz.com/tdj-news with the following text:

The TDJ News Corps

The annual TDJ News Corps is an initiative geared towards post-secondary students who are interested in writing about jazz. Successful applicants to the TDJ News Corps program are given full media accreditation for the TD Toronto Jazz Festival, granting them unprecedented access to the festival – attending and reviewing concerts for free, interviewing artists and experiencing the festival from behind the scenes. In addition, TDJ News Corps members are assigned a mentor – an experienced music journalist. This year’s mentors are Deirdre Kelly, staff writer at <i>The Globe and Mail</i> and critic at CriticsAtLarge; and Mark Wigmore, Senior Arts Editor at JAZZ.FM91.

Check this page throughout the festival for TDJ News Corps articles – concert reviews, artist interviews and other editorial content.

The 2015 TDJ News Corps is:

<ul>
<li><a href="http://torontojazz.com/cameron-macdonald-tdj-news-corps">Cameron MacDonald, an English student at Ryerson University</li>
<li><a href="http://torontojazz.com/stephanie-matas-tdj-news-corps">Stephanie Matas, a media studies and journalism student at University of Guelph-Humber</li>
</ul>

**Comment by andrewfn** [comment]
I have given both writers blogging priviledges (the same as last year).
I have updated the page. Please note that whenever you reference another page within the site, you should use a relative link, e.g. /cameron-macdonald-tdj-news-corps or it will break the mobile site.
Re-open the issue if there are any problems.
