### ISSUE TITLE
facebook link at bottom of page not working

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#46]
At the bottom of our homepage, the link to "Follow Us On Facebook" is broken. 
Can you take a look and redirect it to the proper FB page - www.facebook.com/torontojazzfest

any progress on bringing those venues to the top of list?  2 weeks to go.  any shows you would like to attend?

**Comment by andrewfn** [comment]
Facebook link fixed.
I'll have a think about what to attend. Any recommendations for blues?

**Comment by brianblain** [comment]
gary clark or booker T
