### ISSUE TITLE
increase maximum size for audio files to 15 mg

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#47]
Darcy was running into a lot of files that were just a bit over 10 meg....

**Comment by andrewfn** [comment]
I have increased it to 15 Mb

**Comment by brianblain** [comment]
*****just uploaded an audio file to Brian Katz and it doesn't want to play.
Did I miss something?  It's a little over 10 meg - it's mp3 and it's a good
file - it plays on itunes. B

On Thu, Jun 4, 2015 at 10:10 PM, Andrew Fountain notifications@github.com
wrote:

> Closed #47 https://github.com/jazzto/2015/issues/47.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2015/issues/47#event-323142631.

## 

Brian Blain
Managing Editor
Toronto Downtown Jazz
82 Bleecker Street, Toronto, ON  M4X 1L8
blain@tojazz.com

www.torontojazz.com
TD Toronto Jazz Festival
June 18-27, 2015

**Comment by andrewfn** [comment]
This has come up before. You have to wait up to 30 mins before songs will play.
Because of the huge load of serving audio, and to give a good response for users, all our audio is served from Amazon.
Every half hour the audio is synced with Amazon's servers. Is it working now?

**Comment by brianblain** [comment]
we're good.
