### ISSUE TITLE
built-in Facebook commenting

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#5]
Don't think we want it front and centre like that (see Radio Deluxe) even when they're good comments.
Is there a way to tuck those comments on another page - or maybe a link to facebook.
It's OK to have a facebook "like" button,  but that's too much real-estate.

**Comment by andrewfn** [comment]
This might be tricky to do but I'm looking at the options.

**Comment by brianblain** [comment]
I'm seeing facebook comments appearing on artist page but the plug in still shows on concert page between concert info and artist info (see Tower of Power)

**Comment by andrewfn** [comment]
Yes. Will get to it soon.

**Comment by andrewfn** [comment]
I have figured out a way to make it go to the bottom. Should be fixed soon!

**Comment by andrewfn** [comment]
I have moved this now. Looks a lot tidier.
