### ISSUE TITLE
Boosting performance during festival

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2015#50]
I am going to use the (free) Cloudflare service to boost the speed of the website, particularly images. I have had great success with other sites. It caches all our images in the cloud and takes the load off our server. It also gives us an extra source for analytics.
I have switched it on for the mobile site and it will start working in the next few hours. Unless there are any problems I will then turn it on for the main site. You should not notice any difference except for near instant page loading, but let me know if you or @joshgrossman notice anything unusual.

**Comment by andrewfn** [comment]
The mobile site seems to be working well with Cloudflare which is now taking 83% of the load of mobile traffic. It only serves the images and static assets but that is the biggest load.
I have started the switch for the main site, which will take 24 hours to complete.
One of the bonuses is that Cloudflare has it's own analytics page which is more accurate than Google since they are actually serving the content.

**Comment by andrewfn** [comment]
There were half a million http requests on the site today! (each page request involves a separate request for each image etc.)
87% of them were handled by Cloudflare, which keeps our site fast and responsive. I'm very pleased with how well it is working.

**Comment by brianblain** [comment]
Nice. I don't suppose there's an easy way to display audio track names...
In the audio page it shows just the artist name and on the artist page it
shows nothing. B

On Monday, June 15, 2015, Andrew Fountain notifications@github.com wrote:

> There were half a million http requests on the site today! (each page
> request involves a separate request for each image etc.)
> 87% of them were handled by Cloudflare, which keeps our site fast and
> responsive. I'm very pleased with how well it is working.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jazzto/2015/issues/50#issuecomment-112259743.

## 

_www.brianblain.ca http://www.brianblain.ca_
_twitter.com/brianblain http://twitter.com/brianblain_
_myspace.com/brianblain http://myspace.com/brianblain_

_reverbnation.com/brianblain http://reverbnation.com/brianblain_
_facebook.com/brianblain.home http://facebook.com/brianblain.home_
_facebook.com/brianblain.musician http://facebook.com/brianblain.musician_

**Comment by andrewfn** [comment]
According to Google we are getting 40%-50% more hits than last year!
