### ISSUE TITLE
Switch site to non-festival mode and archive 2015 festival

### ISSUE THREAD

**Issue by andrewfn** [jazzto/2015#55]
Brian says:

> can you switch the site over to non-festival mode.  Here is the image to replace the old one.

I have switched the site over and archived the old one.
Can you check it out and add a comment here if there is any problem. Otherwise I will close the issue and close this year.

So that I know which issues you would like to carry through into next year, please would you close all the ones we _don't_ need to keep. Thanks.

**Comment by andrewfn** [comment]
> thanks - maybe we could also hide/remove the search bar as well. B

Yes, of course. I forgot that.

**Comment by joshgrossman** [comment]
On the updated home page, the TDJ News item seems to be linking to last year's (i.e. 2014) News. Can you update this to this year?

**Comment by andrewfn** [comment]
Wow that was a tough one to fix.
Nailed it now. Let me know if you spot anything else.
@brianblain - I can re-enable the "upcoming concerts" in the search menu as soon as we have a few more to show.
