### ISSUE TITLE
send links from home page photos to concert page instead of artist page

### ISSUE THREAD

**Issue by joshgrossman** [jazzto/2015#58]
On the home page, in each concert block, there are three active links:  the photo links to the artist page; the concert title links to the concert page; and the venue links to the venue page.  As I'm contacting artists and management to see what can be done to push ticket sales, I'm noticing that many have links on their websites to the artist page, instead of the concert page - I wonder if that's because they're coming to our website and grabbing the link from the image in the concert block on the home page.

Unless this has already been discussed in another forum, is it possible to have the images link directly to the concert page, instead of the artist page?  That is - when someone clicks on the image of KC and the Sunshine Band, can the link go to http://torontojazz.com/concert/kc-and-sunshine-band INSTEAD OF http://torontojazz.com/artist/kc-and-sunshine-band?

The fewer clicks to the ticket link the better, I think...

**Comment by andrewfn** [comment]
That should be possible. I'll take a look at it.
b.t.w. this is the issue queue for the 2015 festival. There's another one for 2016. here: https://github.com/jazzto/2016/issues

**Comment by andrewfn** [comment]
It's done on the main site. I still have to do it on the mobile site.
Check it out and let me know if it works for you.

**Comment by andrewfn** [comment]
Done the mobile page now. I think this is a much better arrangement since people will normally want to go to the concert page.

**Comment by joshgrossman** [comment]
Thanks!

Josh Grossman
Artistic Director
Toronto Downtown Jazz
(416) 928-2033 ext. 27
