### ISSUE TITLE
Ticketmaster link

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#7]
Josh says: I'm creating some concert pages and I notice that the "Buy Tickets" fields are pre-set to include a Ticketmaster link.  In fact, it even seems to show up if I delete that information and publish the page.
Since we're not using Ticketmaster (and since that's a bit of a pain), is it possible to remove that default setting on the concert creation form?

**Comment by andrewfn** [comment]
Removed the default Ticketmaster link
@joshgrossman
