### ISSUE TITLE
remove wishlist box

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#8]
not until we have a replacement

**Comment by brianblain** [comment]
Dragan suggests we can remove the wishlist box and that the ad boxes will just flow up, so I guess there's no replacement.  Thanks for getting the search buttons going on dev - makes the last crunch much easier.  Do we have to be careful where we input stuff till we go live??

**Comment by andrewfn** [comment]
When you are ready to turn off the wish list, it is just an "ad", so go here:
http://torontojazz.com/admin/content/simpleads
and change it to **inactive**
- Never make any changes to the dev site, (unless you are experimenting) because it is thrown away every time I refresh.
