### ISSUE TITLE
add new github user

### ISSUE THREAD

**Issue by brianblain** [jazzto/2015#9]
joelmblain@gmail.com

It looks like there is already an account with this email address. Has he created one already?

**Comment by andrewfn** [comment]
I emailed Joel but not heard back from him. I can't do anything till I know if he has an account already and if so what his username is.

**Comment by brianblain** [comment]
i just sent him a note.  He's pretty busy painting his new apt

**Comment by andrewfn** [comment]
He says he already has an account here @brove
